name: super-netball-analysis
channels:
 - conda-forge
 - defaults
dependencies:
 - matplotlib=3.*
 - numpy=1.*
 - pandas=1.*
 - python=3.7.*
 - scipy=1.*
 - scikit-learn=0.*
 - seaborn=0.*
 - spyder=4.*
 - bokeh=2.*
 - selenium=3.*
 - geckodriver=0.*
 - firefox=79.*
